# Generated by Django 5.0.4 on 2024-05-05 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp5', '0002_rename_name_product_nname_product_date_added_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='nname',
            new_name='name',
        ),
    ]
